project:
  type: website
  output-dir: _site      
  preview:               
    port: 4200

format:
  html:
    theme: cosmo          
    css: styles.css
    include-in-header: "_includes/loader.html"   
    page-layout: full

website:
  navbar:
    # hide the text title
    title: ""
    # your banner image
    logo: images/oceanustv.png
    logo-alt: "Echoes of Oceanus"
    # what clicking the logo should link to
    logo-href: "/"
    background: "#1DB954"       
    foreground: white

    right:
      - text: Home
        href: index.qmd
      - text: Meeting Minutes
        menu:
          - text: Meeting Minutes 1
            href: meetingminutes/meetingminutes1.html

  page-footer:
    center: |
      © {{ 2025 }} OceanusTV · A data visualisation project
