project:
  type: website
  output-dir: _site      
  preview:               
    port: 4200

format:
  html:
    theme: cosmo          
    css: styles.css
    include-in-header: "_includes/loader.html"   
    page-layout: full

website:
  navbar:
    title: ""
    logo: images/oceanustv.png
    logo-alt: "Echoes of Oceanus"
    logo-href: "/"
    background: "#1DB954"       
    foreground: white

    right:
      - text: Home
        href: index.qmd
      - text: Shiny App
        href: https://norhendra-isss608.shinyapps.io/oceanustv/
      - text: User Guide
        href: userguide/userguide.html
      - text: Poster
        href: poster/poster.html
      - text: Proposal
        menu:
          - text: Hendra's
            href: https://norhendra-isss608.netlify.app/take-home_ex/take-home_ex03/take-home_ex03
          - text: Andre's
            href: https://isss608-ay2025-aprilterm.netlify.app/take-home_ex/take-home_ex03/take-home_ex03
          - text: Jin Yao's
            href: https://isss608-blessmebellburve.netlify.app/take-home_ex/take-home_ex03/take-home_ex03        
      - text: Meeting Minutes
        menu:
          - text: Meeting Minutes 1
            href: meetingminutes/meetingminutes1.html

  page-footer:
    center: |
      © {{ 2025 }} OceanusTV · A data visualisation project
